"""
baseline_simulation.py
======================
Runs PAV, sequential Phragmén, and MES (with seqPhragmén completion)
over synthetic approval preference data generated by prefsampling.

Produces a CSV of per-election metrics and a summary statistics table.

Usage
-----
    python baseline_simulation.py               # defaults
    python baseline_simulation.py --help        # all options

Real-world PrefLib data
-----------------------
Download .cat files from https://www.preflib.org and pass via --preflib-dir.
The loader expects the standard PrefLib categorical format.
"""

import argparse
import csv
import itertools
import json
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional

import numpy as np
from abcvoting import abcrules
from abcvoting.preferences import Profile, Voter
from prefsampling.approval import impartial, urn, resampling
from prefsampling.approval.euclidean import euclidean_threshold


# ── Data structures ───────────────────────────────────────────────────────────

@dataclass
class ElectionResult:
    """Stores outcomes and pairwise distances for one election instance."""
    election_id:    str
    data_source:    str          # e.g. "impartial", "urn", "preflib:filename"
    num_voters:     int
    num_candidates: int
    committee_size: int
    # Serialised as sorted lists for CSV
    pav_winners:    list = field(default_factory=list)
    phrag_winners:  list = field(default_factory=list)
    mes_winners:    list = field(default_factory=list)
    # Pairwise Hamming distances (symmetric difference size)
    hamming_pav_phrag:  int = 0
    hamming_pav_mes:    int = 0
    hamming_phrag_mes:  int = 0
    # Approval score of each winning committee (sum over voters of |W ∩ Aᵢ|)
    pav_approval_score:   float = 0.0
    phrag_approval_score: float = 0.0
    mes_approval_score:   float = 0.0
    # Runtime in seconds
    runtime_pav:   float = 0.0
    runtime_phrag: float = 0.0
    runtime_mes:   float = 0.0
    error:         str = ""


# ── Helpers ───────────────────────────────────────────────────────────────────

def ballots_to_profile(ballots: list[set], num_cand: int) -> Profile:
    """Convert a list of approval sets to an abcvoting Profile."""
    profile = Profile(num_cand=num_cand)
    for ballot in ballots:
        profile.add_voter(Voter(approved=sorted(ballot)))
    return profile


def hamming(A: set, B: set) -> int:
    """Symmetric difference size — the natural distance between two committees."""
    return len(A.symmetric_difference(B))


def approval_score(winners: set, ballots: list[set]) -> float:
    """Sum of |W ∩ Aᵢ| across all voters."""
    return sum(len(winners & ballot) for ballot in ballots)


def run_rules(profile: Profile, k: int, ballots: list[set]):
    """
    Run PAV, seqPhragmén, MES on profile.
    Returns (pav_w, phrag_w, mes_w, times_dict) or raises on error.
    """
    t0 = time.perf_counter()
    pav_committees = abcrules.compute_pav(profile, k, resolute=True)
    t_pav = time.perf_counter() - t0

    t0 = time.perf_counter()
    phrag_committees = abcrules.compute_seqphragmen(profile, k, resolute=True)
    t_phrag = time.perf_counter() - t0

    t0 = time.perf_counter()
    mes_committees = abcrules.compute_equal_shares(
        profile, k, resolute=True, completion="seqphragmen"
    )
    t_mes = time.perf_counter() - t0

    pav_w   = set(pav_committees[0])
    phrag_w = set(phrag_committees[0])
    mes_w   = set(mes_committees[0])

    times = dict(pav=t_pav, phrag=t_phrag, mes=t_mes)
    return pav_w, phrag_w, mes_w, times


def make_result(
    election_id: str,
    source: str,
    ballots: list[set],
    num_cand: int,
    k: int,
) -> ElectionResult:
    """Run rules on one election instance and return a filled ElectionResult."""
    result = ElectionResult(
        election_id=election_id,
        data_source=source,
        num_voters=len(ballots),
        num_candidates=num_cand,
        committee_size=k,
    )
    try:
        profile = ballots_to_profile(ballots, num_cand)
        pav_w, phrag_w, mes_w, times = run_rules(profile, k, ballots)

        result.pav_winners   = sorted(pav_w)
        result.phrag_winners = sorted(phrag_w)
        result.mes_winners   = sorted(mes_w)

        result.hamming_pav_phrag  = hamming(pav_w, phrag_w)
        result.hamming_pav_mes    = hamming(pav_w, mes_w)
        result.hamming_phrag_mes  = hamming(phrag_w, mes_w)

        result.pav_approval_score   = approval_score(pav_w, ballots)
        result.phrag_approval_score = approval_score(phrag_w, ballots)
        result.mes_approval_score   = approval_score(mes_w, ballots)

        result.runtime_pav   = round(times["pav"],   4)
        result.runtime_phrag = round(times["phrag"], 4)
        result.runtime_mes   = round(times["mes"],   4)

    except Exception as exc:
        result.error = str(exc)

    return result


# ── Synthetic data generators ─────────────────────────────────────────────────

def generate_impartial(num_voters, num_cand, p, seed):
    return impartial(num_voters=num_voters, num_candidates=num_cand, p=p, seed=seed)


def generate_urn(num_voters, num_cand, p, alpha, seed):
    return urn(num_voters=num_voters, num_candidates=num_cand, p=p, alpha=alpha, seed=seed)


def generate_resampling(num_voters, num_cand, rel_size, phi, seed):
    """
    rel_size = rel_size_central_vote (fraction of candidates in central vote).
    phi      = resampling probability (higher = more homogeneous).
    """
    return resampling(
        num_voters=num_voters,
        num_candidates=num_cand,
        phi=phi,
        rel_size_central_vote=rel_size,
        impartial_central_vote=True,
        seed=seed,
    )


def generate_euclidean(num_voters, num_cand, avg_ballot_size_frac, seed):
    """
    Euclidean model in 2D unit ball, constant-size ballots.
    avg_ballot_size_frac: fraction of candidates each voter approves.
    """
    from prefsampling.approval.euclidean import euclidean_constant_size, EuclideanSpace
    return euclidean_constant_size(
        num_voters=num_voters,
        num_candidates=num_cand,
        rel_num_approvals=avg_ballot_size_frac,
        num_dimensions=2,
        voters_positions=EuclideanSpace.UNIFORM_BALL,
        candidates_positions=EuclideanSpace.UNIFORM_BALL,
        seed=seed,
    )


# ── PrefLib loader ─────────────────────────────────────────────────────────────

def load_preflib_cat(path: Path):
    """
    Parse a PrefLib .cat file into (ballots: list[set[int]], num_cand: int).

    .cat format (categorical / approval):
      Header lines start with #
      Data lines: <multiplicity>: {cand,...},{cand,...},...
      Category 1 = approved, others = not approved (standard for 2-cat files).
    """
    from preflibtools.instances import CategoricalInstance
    ci = CategoricalInstance()
    ci.parse_file(str(path))

    # In a 2-category .cat file, category 1 = approved
    # preferences is a list of (tuple_of_tuples,) where each inner tuple is a category
    ballots = []
    for pref, mult in ci.multiplicity.items():
        # pref is a tuple of tuples; pref[0] is the approved set (category 1)
        if len(pref) >= 1 and pref[0]:
            approved = set(int(c) - 1 for c in pref[0])  # 1-indexed → 0-indexed
        else:
            approved = set()
        for _ in range(mult):
            ballots.append(approved)

    num_cand = ci.num_alternatives
    return ballots, num_cand


# ── Main simulation loop ───────────────────────────────────────────────────────

def run_synthetic(args) -> list[ElectionResult]:
    """Generate synthetic elections across all model/parameter combinations."""
    results = []
    eid = 0

    base_seed = args.seed

    # ── Impartial culture ──
    for n, m, p in itertools.product(args.voters, args.candidates, args.prob):
        k = max(1, m // args.k_ratio)
        for rep in range(args.reps):
            seed = base_seed + eid
            ballots = generate_impartial(n, m, p, seed)
            source = f"impartial_n{n}_m{m}_p{p:.2f}_rep{rep}"
            results.append(make_result(f"syn_{eid:05d}", source, ballots, m, k))
            eid += 1

    # ── Urn model ──
    for n, m, p, alpha in itertools.product(
        args.voters, args.candidates, args.prob, args.alpha
    ):
        k = max(1, m // args.k_ratio)
        for rep in range(args.reps):
            seed = base_seed + eid
            ballots = generate_urn(n, m, p, alpha, seed)
            source = f"urn_n{n}_m{m}_p{p:.2f}_a{alpha:.2f}_rep{rep}"
            results.append(make_result(f"syn_{eid:05d}", source, ballots, m, k))
            eid += 1

    # ── Resampling (correlation model) ──
    # rel_size = fraction of candidates in central vote (reuse --prob sweep)
    for n, m, rel_size, phi in itertools.product(
        args.voters, args.candidates, args.prob, args.phi
    ):
        k = max(1, m // args.k_ratio)
        for rep in range(args.reps):
            seed = base_seed + eid
            ballots = generate_resampling(n, m, rel_size, phi, seed)
            source = f"resampling_n{n}_m{m}_rs{rel_size:.2f}_phi{phi:.2f}_rep{rep}"
            results.append(make_result(f"syn_{eid:05d}", source, ballots, m, k))
            eid += 1

    # ── Euclidean threshold ──
    for n, m, thr in itertools.product(args.voters, args.candidates, args.threshold):
        k = max(1, m // args.k_ratio)
        for rep in range(args.reps):
            seed = base_seed + eid
            ballots = generate_euclidean(n, m, thr, seed)
            source = f"euclidean_n{n}_m{m}_thr{thr:.2f}_rep{rep}"
            results.append(make_result(f"syn_{eid:05d}", source, ballots, m, k))
            eid += 1

    return results


def run_preflib(preflib_dir: Path, k_ratio: int) -> list[ElectionResult]:
    """Load all .cat files in preflib_dir and run the three rules on each."""
    results = []
    cat_files = sorted(preflib_dir.glob("*.cat"))
    if not cat_files:
        print(f"  [warn] No .cat files found in {preflib_dir}")
        return results

    for i, path in enumerate(cat_files):
        try:
            ballots, num_cand = load_preflib_cat(path)
            if num_cand < 2 or len(ballots) < 2:
                continue
            k = max(1, num_cand // k_ratio)
            source = f"preflib:{path.name}"
            results.append(
                make_result(f"pl_{i:04d}", source, ballots, num_cand, k)
            )
        except Exception as exc:
            print(f"  [error] {path.name}: {exc}")

    return results


# ── Output ────────────────────────────────────────────────────────────────────

NUMERIC_FIELDS = [
    "hamming_pav_phrag", "hamming_pav_mes", "hamming_phrag_mes",
    "pav_approval_score", "phrag_approval_score", "mes_approval_score",
    "runtime_pav", "runtime_phrag", "runtime_mes",
]

def write_csv(results: list[ElectionResult], path: Path):
    if not results:
        print("No results to write.")
        return
    fieldnames = [f for f in asdict(results[0]).keys()
                  if f not in ("pav_winners", "phrag_winners", "mes_winners")]
    fieldnames += ["pav_winners_str", "phrag_winners_str", "mes_winners_str"]

    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in results:
            row = asdict(r)
            row["pav_winners_str"]   = json.dumps(row.pop("pav_winners"))
            row["phrag_winners_str"] = json.dumps(row.pop("phrag_winners"))
            row["mes_winners_str"]   = json.dumps(row.pop("mes_winners"))
            writer.writerow(row)
    print(f"Results written → {path}")


def print_summary(results: list[ElectionResult]):
    """Print a quick summary broken down by data_source prefix (model type)."""
    ok = [r for r in results if not r.error]
    err = [r for r in results if r.error]

    print(f"\n{'='*60}")
    print(f"SUMMARY  ({len(ok)} elections, {len(err)} errors)")
    print(f"{'='*60}")

    # Group by model prefix
    groups: dict[str, list] = {}
    for r in ok:
        model = r.data_source.split("_")[0].split(":")[0]
        groups.setdefault(model, []).append(r)

    for model, rs in sorted(groups.items()):
        h_pp = np.mean([r.hamming_pav_phrag for r in rs])
        h_pm = np.mean([r.hamming_pav_mes   for r in rs])
        h_fm = np.mean([r.hamming_phrag_mes  for r in rs])
        print(f"\n  Model: {model}  (n={len(rs)})")
        print(f"    Mean Hamming PAV↔Phrag : {h_pp:.3f}")
        print(f"    Mean Hamming PAV↔MES   : {h_pm:.3f}")
        print(f"    Mean Hamming Phrag↔MES : {h_fm:.3f}")
        # Fraction of elections where all three agree
        agree = sum(1 for r in rs if r.hamming_pav_phrag == 0
                    and r.hamming_pav_mes == 0) / len(rs)
        print(f"    All-agree rate         : {agree:.1%}")

    if err:
        print(f"\n  Errors ({len(err)}):")
        for r in err[:5]:
            print(f"    {r.election_id} [{r.data_source}]: {r.error}")
        if len(err) > 5:
            print(f"    ... and {len(err)-5} more")

    print(f"{'='*60}\n")


# ── CLI ───────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description="Baseline: PAV / Phragmén / MES over synthetic & PrefLib datasets"
    )
    # Synthetic parameters
    p.add_argument("--voters",     nargs="+", type=int,   default=[50, 100],
                   help="Voter counts to sweep (default: 50 100)")
    p.add_argument("--candidates", nargs="+", type=int,   default=[10, 20],
                   help="Candidate counts to sweep (default: 10 20)")
    p.add_argument("--prob",       nargs="+", type=float, default=[0.2, 0.4],
                   help="Approval probability p (default: 0.2 0.4)")
    p.add_argument("--alpha",      nargs="+", type=float, default=[0.5],
                   help="Urn alpha (default: 0.5)")
    p.add_argument("--phi",        nargs="+", type=float, default=[0.5],
                   help="Resampling phi (default: 0.5)")
    p.add_argument("--threshold",  nargs="+", type=float, default=[0.4],
                   help="Euclidean threshold (default: 0.4)")
    p.add_argument("--reps",       type=int,   default=10,
                   help="Repetitions per parameter combination (default: 10)")
    p.add_argument("--k-ratio",    type=int,   default=5,
                   help="Committee size = num_candidates // k_ratio (default: 5)")
    p.add_argument("--seed",       type=int,   default=42,
                   help="Base random seed (default: 42)")
    # PrefLib
    p.add_argument("--preflib-dir", type=Path, default=None,
                   help="Directory containing PrefLib .cat files (optional)")
    # Output
    p.add_argument("--out", type=Path, default=Path("results_baseline.csv"),
                   help="Output CSV path (default: results_baseline.csv)")
    p.add_argument("--no-synthetic", action="store_true",
                   help="Skip synthetic data, run PrefLib only")
    return p.parse_args()


def main():
    args = parse_args()
    all_results: list[ElectionResult] = []

    if not args.no_synthetic:
        print("Running synthetic elections...")
        syn = run_synthetic(args)
        all_results.extend(syn)
        print(f"  Synthetic: {len(syn)} elections")

    if args.preflib_dir and args.preflib_dir.exists():
        print(f"Running PrefLib elections from {args.preflib_dir}...")
        pl = run_preflib(args.preflib_dir, args.k_ratio)
        all_results.extend(pl)
        print(f"  PrefLib: {len(pl)} elections")
    elif args.preflib_dir:
        print(f"[warn] PrefLib directory not found: {args.preflib_dir}")

    write_csv(all_results, args.out)
    print_summary(all_results)


if __name__ == "__main__":
    main()
